# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'Free Trial(1)(d535d714-e3f4-4e02-9456-7b1551d77645)'
    subscriptionName: 'd535d714-e3f4-4e02-9456-7b1551d77645'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'NCPL-Demo-Group'
    location: 'South India'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/spundanlabs/azure-devops-arm/master/101-vm-simple-windows/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/spundanlabs/azure-devops-arm/master/101-vm-simple-windows/azuredeploy.parameters.json'
    deploymentMode: 'Complete'